welp_mailchimp:
    api_key: 0d497504e1c7fc91335cc96aa1e516f1-us18

    lists:
        05c0809975:
            subscriber_provider: 'votre_app.provider1' # provider fourni en cas de synchronisation totale
            webhook_secret: 'thisIsASecret' # webhook secret qui permet de sécuriser la liaison entre MailChimp et votre application
            webhook_url: 'https://myapp.com/mailchimp/webhook/endpoint' # L'url webhook en enregistré dans la liste MailChimp
            merge_fields:
                -
                    tag: FNAME
                    name: First Name
                    type: text
                    public: true
                -
                    tag: LNAME
                    name: Last Name
                    type: text
                    public: true